global:
  hosts:
    domain: nip.io
    externalIP: 10.0.2.15 
  edition: ce
  ingress:
      enabled: false

certmanager-issuer:
  email: {} 

certmanager:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

gitlab-runner:
  install: false

registry:
  enabled: false

nginx-ingress:
  enabled: false

postgresql:
  sharedBuffers: "32MB"
  maxConnections: 30
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m

redis:
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 50m


gitlab:
  kas:
    enabled: false

  webservice:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi 
      limits:
        cpu: 1
        memory: 1Gi
  puma:
    threads:
      min: 1
      max: 2
    workerMaxMemory: 500


  sidekiq:
    resources:
      requests:
        cpu: 300m
        memory: 512Mi 
      limits:
        cpu: 1 
        memory: 1Gi 
