# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "deordoneS" do |control|
    control.vm.hostname = "deordoneS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.name = "IoT1"
    end
    control.vm.provision "file", source: "./conf/config-map.yml", destination: "/home/vagrant/"
    control.vm.provision "file", source: "./conf/services.yml", destination: "/home/vagrant/"
    control.vm.provision "file", source: "./conf/deployments.yml", destination: "/home/vagrant/"
    control.vm.provision "file", source: "./conf/ingress.yml", destination: "/home/vagrant/"
    control.vm.provision "shell", path: "script/setup.sh"
  end
end
