# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  
  config.vm.provision "shell", path: "server/setup.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "deordoneS" do |control|
    control.vm.hostname = "deordoneS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.name = "IoT1"
    end
    # control.vm.provision
  end

  config.vm.define "deordoneSW" do |control|
    control.vm.hostname = "deordoneSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vb|
      vb.name = "IoT2"
    end
    # control.vm.provision
  end
end
