# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "deordoneS" do |control|
    control.vm.hostname = "deordoneS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.name = "IoT1"
    end
    control.vm.provision "shell", path: "server/setup.sh", args: "controller"
  end

  config.vm.define "deordoneSW" do |agent|
    agent.vm.hostname = "deordoneSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provider "virtualbox" do |vb|
      vb.name = "IoT2"
    end
    agent.vm.provision "shell", path: "server/setup.sh", args: "agent"
  end
end
