# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20191107.0.0"

  config.vm.define "deordoneS" do |control|
    control.vm.hostname = "deordoneS"
    config.vm.network "private_network", ip: "192.168.56.110"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "IoT1"
      vb.memory = 1024
      vb.cpus = 1
    end
    #config.vm.provision
  end

  config.vm.define "deordoneSW" do |control|
    control.vm.hostname = "deordoneSW"
    config.vm.network "private_network", ip: "192.168.56.111"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "IoT2"
      vb.memory = 1024
      vb.cpus = 1
    end
   # config.vm.provision
  end

end
