# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 4
  end

  config.vm.define "deordoneS" do |control|
    control.vm.hostname = "deordoneS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.network "forwarded_port", guest: 8080, host: 8080
    control.vm.provider "virtualbox" do |vb|
      vb.name = "IoT1"
    end
    control.vm.provision "shell", path: "scripts/setup.sh"
  end
end
